version: '3.8'

services:
  postgress:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: npg_w1hrGj2pYxTJ
      POSTGRES_DB: neondb  
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  app:
    build: .
    container_name: nextjs_app
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL: postgresql://neondb_owner:npg_w1hrGj2pYxTJ@ep-soft-meadow-a8lrm0eq-pooler.eastus2.azure.neon.tech/neondb?sslmode=require
    depends_on:
      - postgres

volumes:
  postgres_data:
